## Built-In Sequences

1. Container sequences (can hold items of different types) <br/>
&nbsp;&nbsp;&nbsp;&nbsp; list, tuple, collections

2. Flat sequences (hold items of one type) <br/>
&nbsp;&nbsp;&nbsp;&nbsp; str, bytes, bytesarray, array.array

## List comprehensions and Generator Expessions
- List comprehension -> for List
- Generator expression -> for other kinds of sequences

In [1]:
# Normal for-loop style
symbols = '$¢£¥€¤'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))
codes

[36, 162, 163, 165, 8364, 164]

In [3]:
# List comprehension style
symbols = '$¢£¥€¤'
codes = [ord(symbol) for symbol in symbols]
codes

[36, 162, 163, 165, 8364, 164]

### Cartesian Products

In [4]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

tshirts = [(color, size) for color in colors for size in sizes]
tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [5]:
# or in more readable-way
tshirts = [(color, size) for color in colors 
                         for size in sizes]

## Generator Expressions
To initialize tuples, array and other type of sequences, we can use listcomp. <br/>
But genexp saves memory because it yield items one by one using the iterator protocol.

In [6]:
# Use tuple to generate generator
symbols = '$¢£¥€¤'
tuple(ord(symbol) for symbol in symbols)

(36, 162, 163, 165, 8364, 164)

In [7]:
# Or use array.array with 2 arguments (1st = Storage type, 2nd = Data)
import array
array.array('I', (ord(symbol) for symbol in symbols))

array('I', [36, 162, 163, 165, 8364, 164])

In [9]:
# User Generator for cartesian products
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts_gen = ('%s %s' % (c, s) for c in colors for s in sizes)

for tshirt in tshirts_gen:
    print(tshirt)

black S
black M
black L
white S
white M
white L


### Tuples are not just immutable lists
### Tuple as records

In [14]:
lax_coordinates = (33.9425, -118.408056)

# Unpacking tuple
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
lattitude, longitude = lax_coordinates

traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]

for passport in sorted(traveler_ids):
    print('%s/%s' % passport)

BRA/CE342567
ESP/XDA205856
USA/31195855


In [12]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


### Nested Tuple Unpacking

In [19]:
metro_areas = [('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
              ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),     
              ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
              ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),     
              ('Sao Paulo', 'BR', 19.649, (-23.547778, -46.635833)),]

fmt = "{:15} | {:9.4f} | {:9.4f}"

for name, cc, pop, (lat, longt) in metro_areas:
    if longt <= 0:
        print(fmt.format(name, lat, longt))

Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
Sao Paulo       |  -23.5478 |  -46.6358


### Named Tuples

In [22]:
from collections import namedtuple


City  = namedtuple('City', 'name country population coordinates')
tokyo = City("Tokyo", "JP", 36.933, (35.689722, 139.691667))
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))

In [23]:
tokyo.population, tokyo.coordinates, tokyo[1]

(36.933, (35.689722, 139.691667), 'JP')

In [25]:
City._fields

('name', 'country', 'population', 'coordinates')

In [28]:
## use named tuple as another item in tuple

# Named Tuple - Lat Long
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ("Delhi NCR", "IN", 21.935, LatLong(28.123, 77.23123))

# Named Tuple - City
delhi = City._make(delhi_data)

In [29]:
delhi._asdict()

{'name': 'Delhi NCR',
 'country': 'IN',
 'population': 21.935,
 'coordinates': LatLong(lat=28.123, long=77.23123)}

In [ ]:
for key, value in delhi._asdict().items():
    print(key + ":", value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.123, long=77.23123)


- Tuple supports all list methods
- Except **adding**, **removing** items
- Tuple also do not have __reversed__ method

### Slicing

In [35]:
# basic
l = [10, 20, 30, 40, 50 ,60]

l[:2], l[2:]

([10, 20], [30, 40, 50, 60])

In [36]:
l[:3], l[3:]

([10, 20, 30], [40, 50, 60])

### Slice objects
s[a:b:c] can be use to specific stride step ***c*** <br/>

seq[start, stop, step] is seq.__getitem__(slice(start, stop, step))

In [39]:
s = 'bicycle'

s[::3], s[::-1], s[::-2]

('bye', 'elcycib', 'eccb')

In [40]:
invoice = """
0.....6.................................40........52...55........
1909  Pimoroni PiBrella                     $17.50    3    $52.50
1489  6mm Tactile Switch x20                 $4.95    2     $9.90
1510  Panavise Jr. - PV-201                 $28.00    1    $28.00
1601  PiTFT Mini Kit 320x240                $34.95    1    $34.95
"""

In [46]:
SKU = slice(0, 6)
DESCRIPTION = slice(6, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)

line_items = invoice.split("\n")[2:]
for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

    $17.50   Pimoroni PiBrella                 
     $4.95   6mm Tactile Switch x20            
    $28.00   Panavise Jr. - PV-201             
    $34.95   PiTFT Mini Kit 320x240            
 


In [58]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [59]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [60]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [61]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [62]:
l[2:5] = 100

TypeError: can only assign an iterable

In [57]:
l[2:5] = [100]
l

### Managing Ordered Sequences with Bisect

```bisect``` and ```insort``` are built-in function in python to perform binary search algorithm

In [2]:
import bisect

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30] 
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d}@ {1:2d} {2}{0:<2d}'

In [4]:
def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)
        offset = position * '   |'
        print(ROW_FMT.format(needle, position, offset))

In [24]:
test_list = [1, 2, 3, 4, 5, 6, 7, 8, 10, 12 , 20, 20, 31, 37]
bisect.bisect_left(test_list, 11)

9

In [25]:
# Bisect function selection
## Left
bisect_fn = bisect.bisect_left

print('DEMO:', bisect_fn.__name__)
print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))

demo(bisect_fn)

DEMO: bisect_left
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31@ 14    |   |   |   |   |   |   |   |   |   |   |   |   |   |31
30@ 13    |   |   |   |   |   |   |   |   |   |   |   |   |30
29@ 12    |   |   |   |   |   |   |   |   |   |   |   |29
23@  9    |   |   |   |   |   |   |   |   |23
22@  9    |   |   |   |   |   |   |   |   |22
10@  5    |   |   |   |   |10
 8@  4    |   |   |   |8 
 5@  2    |   |5 
 2@  1    |2 
 1@  0 1 
 0@  0 0 


In [26]:
## Normal bisect
bisect_fn = bisect.bisect

print('DEMO:', bisect_fn.__name__)
print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))

demo(bisect_fn)

DEMO: bisect_right
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31@ 14    |   |   |   |   |   |   |   |   |   |   |   |   |   |31
30@ 14    |   |   |   |   |   |   |   |   |   |   |   |   |   |30
29@ 13    |   |   |   |   |   |   |   |   |   |   |   |   |29
23@ 11    |   |   |   |   |   |   |   |   |   |   |23
22@  9    |   |   |   |   |   |   |   |   |22
10@  5    |   |   |   |   |10
 8@  5    |   |   |   |   |8 
 5@  3    |   |   |5 
 2@  1    |2 
 1@  1    |1 
 0@  0 0 


In [29]:
# Use case of bisect to search position of item
def grade(score, breakpoints = [60, 70, 80, 90], grades = "FDCBA"):
    i = bisect.bisect(breakpoints, score)
    return grades[i]

[grade(score) for score in [33, 99, 77, 70, 89, 90, 100]]    

['F', 'A', 'C', 'C', 'B', 'A', 'A']

Use ```bisect.insort``` for inserting

In [35]:
import random

SIZE = 7
random.seed(1729)

my_list = []
for i in range(SIZE):
    # Random generate number base on given range
    new_item = random.randrange(SIZE*2)

    # Insert nem item by maintaining order of item in sequence
    bisect.insort(my_list, new_item)
    print('%2d ->'%new_item, my_list)

10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


## When not to use list ?
- When list will be use to store only number. <br/>
&nbsp;-> Array will store only bytes representing (save more memory)

### Array

In [36]:
from array import array
from random import random

# 'd' = double-precision floats s
floats = array('d', (random() for i in range(10**7)))
floats[-1]

0.5963321947530882

In [37]:
fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()

In [39]:
floats2 = array('d')

fp = open('floats.bin','rb')
floats2.fromfile(fp, 10**7) 
fp.close()

floats2[-1]

0.5963321947530882

In [40]:
floats[-1] == floats2[-1]

True

### Memory Views
- Built-in memoryview class is shared-memory sequence type.
- It allow us to share memory between data-structures without copying.
- Very importance for large dataset.

In [43]:
# 'h' = signed intergers
numbers = array('h', [-2, -1, 0, 1, 2])
memb = memoryview(numbers)
len(memb)

5

In [44]:
memb[0]

-2

In [45]:
# Convert memb to unsigned char ('B')
memb_oct = memb.cast('B')
memb_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [46]:
memb_oct[5] = 4

In [47]:
numbers

array('h', [-2, -1, 1024, 1, 2])

### Scipy and Numpy
- For advanced array and matrix operations, NumPy and Scipy are the reason why Python become mainstream in scientific computing appliation.
- Scipy is library wrriten on top of NumPy.

In [51]:
import numpy

a = numpy.arange(12)
a, type(a), a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), numpy.ndarray, (12,))

In [52]:
a.shape = 3, 4 # Mutate shape of numpy array
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a[2]

array([ 8,  9, 10, 11])

In [54]:
a[2, 1]

9

In [55]:
a[:, 1] # Select all row with only column 1

array([1, 5, 9])

In [56]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## Deques and Queues

In [64]:
from collections import deque

dq = deque(range(10), maxlen = 10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [66]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [67]:
dq.appendleft(-1)
dq 

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
dq.extend([11, 22, 33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

In [69]:
dq.extendleft([10,20,30,40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])

In [70]:
for item in dq:
    print(item)

40
30
20
10
3
4
5
6
7
8
